### ISSUE TITLE
Process emails

### ISSUE THREAD

**Issue by gabriel-v** [hoover/snoop2#2]
Use the new method (create a `Directory` for all `File`s that have children) to populate email attachments.
Use https://github.com/hoover/snoop/blob/master/snoop/emails.py for reference.

- [x] Process `eml` file headers
- [x] Process `eml` file attachments (and create the file structures)
- [x] Process `msg` files by turning them into `eml` first
- [x] Process `emlx` + `emlxpart` files by turning them into `eml` files

**Comment by gabriel-v** [comment]
only have to process email attachments and we're done

**Comment by mgax** [comment]
aaand we have attachments, all done. https://github.com/hoover/snoop2/pull/29
