### ISSUE TITLE
Process text/html and text/plain types

### ISSUE THREAD

**Issue by gabriel-v** [hoover/snoop2#3]
Extract the text from plain/html and plain/text files.
Sanitize the html as done in https://github.com/hoover/snoop/blob/master/snoop/html.py to keep current UI functionality.

**Comment by mgax** [comment]
Tika handles text extraction: https://github.com/hoover/snoop2/blob/master/snoop/data/analyzers/tika.py#L9-L10.

We still need to output the safe html.
